# Generated by Django 4.1 on 2022-08-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('gender', models.CharField(choices=[('Homem', 'Homem'), ('Mulher', 'Mulher'), ('Outros', 'Outros'), ('Prefiro não informar', 'Prefiro não informar')], max_length=20, null=True)),
                ('district', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=3)),
                ('marital_status', models.CharField(choices=[('casado(a)', 'casado(a)'), ('solteiro(a)', 'solteiro(a)')], max_length=20)),
                ('profile', models.CharField(default='brando', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collight.customer')),
            ],
        ),
    ]
