from django.test import TestCase
from rest_framework import status
from rest_framework.test import APIClient
from models.payment_methods import Payment

class PaymentTestCase():

    fixtures = [""]

    def setUp(self) -> None:
        self.clientAPI = APIClient()

    def test_upload_fixture(self):
        """Check the data generated by fixtures"""
        all_payment = Payment.objects.all()
        self.assertEqual(len(all_payment), 10)