from django.test import TestCase
from rest_framework import status
from rest_framework.test import APIClient
from models.customer import Customer

class CustomerTestCase():

    fixtures = [""]

    def setUp(self) -> None:
        self.clientAPI = APIClient()

    def test_upload_fixture(self):
        """Check the data generated by fixtures"""
        all_customers = Customer.objects.all()
        self.assertEqual(len(all_customers), 10)

    def test_(self):
        """ """
        # dado

        # quando
        # response = self.clientAPI.post("", , format="json")

        # entao
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)